env: "dev"
server:
  host: "127.0.0.1"
  port: 8080
db:
  driver: "postgres"
  source: "postgresql://root:secret@localhost:5432/ecom?sslmode=disable"
token:
  symmetric_key: 12345678901234567890123456789012
  access_duration: 15m
