// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Product struct {
	ID                 int64          `json:"id"`
	Name               string         `json:"name"`
	DescriptionLong    sql.NullString `json:"description_long"`
	DescriptionShort   sql.NullString `json:"description_short"`
	Price              int32          `json:"price"`
	ProductTypeID      int64          `json:"product_type_id"`
	ProductCategoryID  sql.NullInt64  `json:"product_category_id"`
	ProductInventoryID int64          `json:"product_inventory_id"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type ProductCategory struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ProductInventory struct {
	ID        int64     `json:"id"`
	Quantity  int32     `json:"quantity"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ProductOrder struct {
	ID        int64     `json:"id"`
	Owner     string    `json:"owner"`
	Quantity  int32     `json:"quantity"`
	ProductID int64     `json:"product_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ProductType struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
