// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductCategory(ctx context.Context, name string) (ProductCategory, error)
	CreateProductInventory(ctx context.Context, quantity int32) (ProductInventory, error)
	CreateProductOrder(ctx context.Context, arg CreateProductOrderParams) (ProductOrder, error)
	CreateProductType(ctx context.Context, name string) (ProductType, error)
	DeleteProduct(ctx context.Context, id int64) error
	DeleteProductCategory(ctx context.Context, id int64) error
	DeleteProductInventory(ctx context.Context, id int64) error
	DeleteProductOrder(ctx context.Context, id int64) error
	DeleteProductType(ctx context.Context, id int64) error
	GetProduct(ctx context.Context, id int64) (Product, error)
	GetProductCategory(ctx context.Context, id int64) (ProductCategory, error)
	GetProductInventory(ctx context.Context, id int64) (ProductInventory, error)
	GetProductInventoryForProduct(ctx context.Context, id int64) (ProductInventory, error)
	GetProductInventoryForProductForUpdate(ctx context.Context, id int64) (ProductInventory, error)
	GetProductOrder(ctx context.Context, id int64) (ProductOrder, error)
	GetProductType(ctx context.Context, id int64) (ProductType, error)
	ListProductCategories(ctx context.Context, arg ListProductCategoriesParams) ([]ProductCategory, error)
	ListProductInventories(ctx context.Context, arg ListProductInventoriesParams) ([]ProductInventory, error)
	ListProductOrders(ctx context.Context, arg ListProductOrdersParams) ([]ProductOrder, error)
	ListProductTypes(ctx context.Context, arg ListProductTypesParams) ([]ProductType, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	UpdateProductCategory(ctx context.Context, arg UpdateProductCategoryParams) (ProductCategory, error)
	UpdateProductInventoryQuantity(ctx context.Context, arg UpdateProductInventoryQuantityParams) (ProductInventory, error)
	UpdateProductInventoryQuantityForProduct(ctx context.Context, arg UpdateProductInventoryQuantityForProductParams) (ProductInventory, error)
	UpdateProductName(ctx context.Context, arg UpdateProductNameParams) (Product, error)
	UpdateProductOrderQuantity(ctx context.Context, arg UpdateProductOrderQuantityParams) (ProductOrder, error)
	UpdateProductType(ctx context.Context, arg UpdateProductTypeParams) (ProductType, error)
}

var _ Querier = (*Queries)(nil)
